### ISSUE TITLE
SetTitleGame Error

### ISSUE THREAD

**Issue by filipeaugustosantos** [SuchByte/Macro-Deck-Twitch-Plugin#12]
The SetTitleGame action returns an authentication error:

follow the logs:

```
21:20:33 [Twitch Plugin] [Info] >> Set title to Vamos de hablação and game to Just Talk
21:20:34 [Twitch Plugin] [Error] >> Error while setting title and game: Your request failed because either: 
 1. Your ClientID was invalid/not set. 
 2. Your refresh token was invalid. 
 3. You requested a username when the server was expecting a user ID.
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.HandleWebException(HttpResponseMessage errorResp)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequestAsync(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass15_0.<<TwitchPatchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at TwitchLib.Api.Core.ApiBase.TwitchPatchAsync(String resource, ApiVersion api, String payload, List`1 getParams, String accessToken, String clientId, String customBase)
   at SuchByte.TwitchPlugin.TwitchHelper.SetTitleGameAsync(String title, String game) in D:\Temp\SuchByte.TwitchPlugin\TwitchHelper.cs:line 159
```

**Comment by sshogrin** [comment]
I haven't seen an error log, but I can't change stream titles either.
